### PR TITLE
Fix #61: updated to work with v 1.11

### LINKED ISSUE #61: Update to make compatible with Reaction v1.11.0

### PR DESCRIPTION
**Pull request by Akarshit**
Closes #61 

# Changed made
1. Schemas now live in a separate repo. So updated the `import` in all the files.
2. Validation has been moved from collection to schema.
3. Button now doesn't accept React node as label.

### CODE REVIEW

**Comment by mostlyjason** [comment]
I got this built but viewing a product page like http://localhost:3000/product/reaction-mug gives me the below error. Might be something wrong in my env but figured I should report this. 

```
Uncaught TypeError: this.renderInventoryStatus is not a function
    at Variant.render (variant.js:48)
    at finishClassComponent (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:253835)
    at updateClassComponent (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:253812)
    at beginWork (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:254187)
    at performUnitOfWork (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256186)
    at workLoop (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256250)
    at HTMLUnknownElement.callCallback (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246504)
    at Object.invokeGuardedCallbackDev (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246543)
    at invokeGuardedCallback (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246400)
    at renderRoot (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256328)
render @ variant.js:48
finishClassComponent @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:253835
updateClassComponent @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:253812
beginWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:254187
performUnitOfWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256186
workLoop @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256250
callCallback @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246504
invokeGuardedCallbackDev @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246543
invokeGuardedCallback @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246400
renderRoot @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256328
performWorkOnRoot @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256976
performWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256929
requestWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256840
scheduleWorkImpl @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256694
scheduleWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256651
enqueueSetState @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:252174
Component.setState @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:66128
onData @ compose.js:80
composer @ reactionLayout.js:126
(anonymous) @ tracker.js:36
Tracker.Computation._compute @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:339
Tracker.Computation._recompute @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:358
Tracker._runFlush @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:532
onGlobalMessage @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:448
postMessage (async)
setImmediate @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:468
requireFlush @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:151
Tracker.Computation.invalidate @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:292
Tracker.Dependency.changed @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:459
(anonymous) @ cursor.js:296
SQp.runTask @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:782
SQp.flush @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:811
SQp.drain @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:820
resumeObservers @ local_collection.js:306
endUpdate @ collection.js:234
store.(anonymous function) @ livedata_connection.js:310
(anonymous) @ livedata_connection.js:1228
_performWrites @ livedata_connection.js:1227
_flushBufferedWrites @ livedata_connection.js:1183
_livedata_data @ livedata_connection.js:1149
onMessage @ livedata_connection.js:1679
(anonymous) @ browser.js:181
forEachCallback @ common.js:30
socket.onmessage @ browser.js:180
REventTarget.dispatchEvent @ sockjs-0.3.4.js:87
SockJS._dispatchMessage @ sockjs-0.3.4.js:1072
SockJS._didMessage @ sockjs-0.3.4.js:1130
that.ws.onmessage @ sockjs-0.3.4.js:1277
modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:255709 The above error occurred in the <Reaction(Variant)> component:
    in Reaction(Variant) (created by SortableItem)
    in SortableItem (created by DragSource(SortableItem))
    in DragSource(SortableItem) (created by DropTarget(DragSource(SortableItem)))
    in DropTarget(DragSource(SortableItem)) (created by Reaction(VariantList))
    in Reaction(EditContainer) (created by Tracker(Reaction(EditContainer)))
    in Tracker(Reaction(EditContainer)) (created by Reaction(VariantList))
    in ul (created by Reaction(VariantList))
    in div (created by Reaction(VariantList))
    in Reaction(VariantList) (created by VariantListContainer)
    in Reaction(DragDropProvider) (created by VariantListContainer)
    in VariantListContainer (created by Reaction(VariantListContainer))
    in Reaction(VariantListContainer) (created by ReactionLayout)
    in div (created by ReactionLayout)
    in div (created by ReactionLayout)
    in ReactionLayout (created by Tracker(ReactionLayout))
    in Tracker(ReactionLayout) (created by Reaction(ProductDetail))
    in div (created by Reaction(ProductDetail))
    in div (created by Reaction(ProductDetail))
    in div (created by Reaction(ProductDetail))
    in Reaction(ProductDetail) (created by ProductDetailContainer)
    in div (created by StyleRoot)
    in StyleRoot (created by ProductDetailContainer)
    in ProductDetailContainer (created by Tracker(ProductDetailContainer))
    in Tracker(ProductDetailContainer)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:255709
captureError @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256502
renderRoot @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256353
performWorkOnRoot @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256976
performWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256929
requestWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256840
scheduleWorkImpl @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256694
scheduleWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256651
enqueueSetState @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:252174
Component.setState @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:66128
onData @ compose.js:80
composer @ reactionLayout.js:126
(anonymous) @ tracker.js:36
Tracker.Computation._compute @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:339
Tracker.Computation._recompute @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:358
Tracker._runFlush @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:532
onGlobalMessage @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:448
postMessage (async)
setImmediate @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:468
requireFlush @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:151
Tracker.Computation.invalidate @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:292
Tracker.Dependency.changed @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:459
(anonymous) @ cursor.js:296
SQp.runTask @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:782
SQp.flush @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:811
SQp.drain @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:820
resumeObservers @ local_collection.js:306
endUpdate @ collection.js:234
store.(anonymous function) @ livedata_connection.js:310
(anonymous) @ livedata_connection.js:1228
_performWrites @ livedata_connection.js:1227
_flushBufferedWrites @ livedata_connection.js:1183
_livedata_data @ livedata_connection.js:1149
onMessage @ livedata_connection.js:1679
(anonymous) @ browser.js:181
forEachCallback @ common.js:30
socket.onmessage @ browser.js:180
REventTarget.dispatchEvent @ sockjs-0.3.4.js:87
SockJS._dispatchMessage @ sockjs-0.3.4.js:1072
SockJS._didMessage @ sockjs-0.3.4.js:1130
that.ws.onmessage @ sockjs-0.3.4.js:1277
meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:992 Exception from Tracker recompute function:
meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:992 TypeError: this.renderInventoryStatus is not a function
    at Variant.render (variant.js:48)
    at finishClassComponent (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:253835)
    at updateClassComponent (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:253812)
    at beginWork (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:254187)
    at performUnitOfWork (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256186)
    at workLoop (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256250)
    at HTMLUnknownElement.callCallback (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246504)
    at Object.invokeGuardedCallbackDev (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246543)
    at invokeGuardedCallback (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:246400)
    at renderRoot (modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256328)
modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:67542 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the Reaction(VariantListContainer) component.
printWarning @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:67542
warning @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:67566
warnAboutUpdateOnUnmounted @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:255728
scheduleWorkImpl @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256699
scheduleWork @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:256651
enqueueSetState @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:252174
Component.setState @ modules.js?hash=adc6a7cd12c0ebd93ffa0bad429cac58d370aecb:66128
onData @ compose.js:80
composer @ variantList.js:201
(anonymous) @ tracker.js:36
Tracker.Computation._compute @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:339
Tracker.Computation._recompute @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:358
Tracker._runFlush @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:532
onGlobalMessage @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:448
postMessage (async)
setImmediate @ meteor.js?hash=b0f12795c8cc1423b5850502871996903f947ed5:468
requireFlush @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:151
Tracker.Computation.invalidate @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:292
Tracker.Dependency.changed @ tracker.js?hash=0e8b5c18d543a28ce43b2f183c26b49ee62196af:459
(anonymous) @ livedata_connection.js:1397
(anonymous) @ livedata_connection.js:1243
_runAfterUpdateCallbacks @ livedata_connection.js:1242
_performWrites @ livedata_connection.js:1232
_flushBufferedWrites @ livedata_connection.js:1183
_livedata_data @ livedata_connection.js:1149
onMessage @ livedata_connection.js:1679
(anonymous) @ browser.js:181
forEachCallback @ common.js:30
socket.onmessage @ browser.js:180
REventTarget.dispatchEvent @ sockjs-0.3.4.js:87
SockJS._dispatchMessage @ sockjs-0.3.4.js:1072
SockJS._didMessage @ sockjs-0.3.4.js:1130
that.ws.onmessage @ sockjs-0.3.4.js:1277
```

**Comment by cyber-claws** [comment]
@mostlyjason in the file `/reaction-swag-shop/blob/master/client/components/product-detail-simple/variant.js` change: 

```jsx
<div className="container-main">
    {this.renderProductGrid()}
    {this.renderLoadingSpinner()}
    {this.renderNotFound()}
</div>
```

to :

```jsx
<div className="alerts">
    {this.renderDeletionStatus()}
    <Components.InventoryBadge className="variant-qty-sold-out variant-badge-label"{...this.props} />
    {this.renderValidationButton()}
    {this.props.editButton}
</div>
```

in the render function.

**Comment by mostlyjason** [comment]
Thanks that did the trick! Works great now. I assume you'll make a commit for that?

**Comment by spencern** [comment]
@Akarshit @zenweasel is this able to be merged or closed?
