### PR TITLE
Modified to work with Reaction 1.12.1

### PR DESCRIPTION
**Pull request by cyber-claws**
Reaction 1.12.1 throws  `ERROR: ReactionProduct.getTag() is not defined`

### CODE REVIEW

**Comment by stunjiturner** [comment]
I keep getting the error reaction Commerce Cannot find module '../../../../../core/collections', 

    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:1:29)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/server/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at plugins.js (server/plugins.js:1:3419)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/covered/.meteor/local/build/programs/server/app/app.js:111627:1
    at /Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/covered/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/covered/.meteor/local/build/programs/server/boot.js:220:19
    at /Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/covered/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/covered/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/stunjiturner/Documents/Sightuary/groups/works+labs/dd/MochaProjects/Javascript/Meteorjs/covered/.meteor/local/build/programs/server/boot.js:470:11

**Comment by zenweasel** [comment]
I believe this has been superseded by https://github.com/reactioncommerce/reaction-swag-shop/pull/66. Closing
